routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/profile', [App\Http\Controllers\ProfileController::class, 'index'])->name('profile');
Route::resources([
    'users' => UserController::class,
    //Provincias / Estados
    'states' => StateController::class,
    'cities' => CityController::class,
    //Emails
    'emails' => EmailController::class,
]);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Support\Facades\DB;

use Illuminate\Support\Facades\Hash;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'type',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Encriptacion de la contraseña
     */
    public function setPasswordAttribute($password){
        if(!empty($password) && $password != 'null'){
            $this->attributes['password'] = Hash::make($password);
        }
    }

    //Relacion con persona
    public function person(){
    	return $this->hasOne('App\Models\Person');
	}

    //Relacion con emails
    public function emails(){
        return $this->hasMany('App\Models\Email');
    }

    //Buscador
    public function scopeSearch($query, $search){
		// return $query->where('name', 'LIKE', "%$search%")
		// 	// ->orWhere('quantity', 'LIKE', "%$search%")
		// 	->orWhere('price', 'LIKE', "%$search%");
		return $query->where(DB::raw("CONCAT(users.name, ' ', dni, ' ', date_birth, ' ', email , ' ', mobile_phone, ' ', cities.name )"), "LIKE", "%$search%");

	}
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\User_Create_Request;
use App\Http\Requests\User_Update_Request;
use Illuminate\Support\Facades\Log;

use App\Models\Country;
use App\Models\User;
use App\Models\Phone;
use App\Models\Person;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = User::search($request['search'])
        ->leftjoin("people",  "people.user_id",  "=", "users.id")
        ->leftjoin("phones",  "phones.id",  "=", "people.phone_id")
        ->leftjoin("cities",  "cities.id",  "=", "people.city_id")
        ->select('users.*', 'people.*')
        ->paginate(15);
   
        $users->each(function($users){
            $users->person;
            $users->person->phone;
            $users->person->city;
        });

        return view('users.index', [
            'users' => $users
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create', [
            'countries' => Country::all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(User_Create_Request $request)
    {
        $user = new User($request->all());
        $user->save();

        $phone = new Phone($request->all());
        $phone->save();

        $person = new Person($request->all());
        $person->user()->associate($user);
        $person->city()->associate($request->city);
        $person->phone()->associate($phone);
        $person->save();

        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $user->person;
        $user->person->phone;
        $user->city;

        return view('users.edit', [
            'user' => $user,
            'countries' => Country::all(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(User_Update_Request $request, $id)
    {
        $user = User::find($id);
        $user->fill($request->all());
        $user->update();

        $phone = Phone::find($user->person->phone->id);
        $phone->fill($request->all());
        $phone->update();

        $person = Person::find($user->person->id);
        $person->fill($request->all());
        $person->user()->associate($user);
        $person->city()->associate($request->city);
        $person->phone()->associate($phone);
        $person->update();

        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        if($user->type != 'admin'){
            $user->delete();
        }
        return redirect()->route('users.index');
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex justify-content-between">
                            {{ __('Nuevo Usuario') }}
                            <a href="{{ route('users.index') }}">
                                {{ __('Usuarios') }}
                            </a>
                        </div>
                    </div>

                    <div class="card-body">

                        <form method="POST" action="{{ route('users.store') }}">
                            @csrf

                            <div class="row mb-3">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>
                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                        name="name" value="{{ old('name') }}" autocomplete="name" autofocus>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="dni" class="col-md-4 col-form-label text-md-right">{{ __('Cédula') }}</label>
                                <div class="col-md-6">
                                    <input id="dni" type="text" class="form-control @error('dni') is-invalid @enderror"
                                        name="dni" value="{{ old('dni') }}" required autocomplete="dni" autofocus>

                                    @error('dni')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="mobile_phone"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Número de Celular') }}</label>
                                <div class="col-md-6">
                                    <input id="mobile_phone" type="text"
                                        class="form-control @error('mobile_phone') is-invalid @enderror" name="mobile_phone"
                                        value="{{ old('mobile_phone') }}" required autocomplete="mobile_phone" autofocus>

                                    @error('mobile_phone')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="date_birth"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Fecha de Nacimiento') }}</label>
                                <div class="col-md-6">
                                    <input id="date_birth" type="date"
                                        class="form-control @error('date_birth') is-invalid @enderror" name="date_birth"
                                        value="{{ old('date_birth') }}" required autocomplete="date_birth" autofocus>

                                    @error('date_birth')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('País') }}</label>
                                <div class="col-md-6">
                                    <select class="form-select" name="country" id="country_id" autocomplete="country"
                                        aria-label="Default select example">
                                        <option selected>Seleccione un país</option>
                                        @foreach ($countries as $country)
                                            <option value="{{ $country->id }}">{{ $country->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="name"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Provincia / Estado') }}</label>
                                <div class="col-md-6">
                                    <select class="form-select" id="state_id" name="state" autocomplete="state"
                                        aria-label="Default select example">
                                        <option selected>Selecione una provincia / estado</option>
                                    </select>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="name"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Ciudad') }}</label>
                                <div class="col-md-6">
                                    <select class="form-select  @error('city') is-invalid @enderror" name="city"
                                        autocomplete="city" id="city_id" aria-label="Default select example">
                                        <option selected>Seleccione una ciudad</option>
                                    </select>

                                    @error('city')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="email"
                                    class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror"
                                        name="email" value="{{ old('email') }}" required autocomplete="email">

                                    @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="password"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password"
                                        class="form-control @error('password') is-invalid @enderror" name="password"
                                        required autocomplete="new-password">

                                    @error('password')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="password-confirm"
                                    class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password-confirm" type="password" class="form-control"
                                        name="password_confirmation" required autocomplete="new-password">
                                </div>
                            </div>

                            <div class="row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Guardar') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script type="text/javascript">
        // Obtener provincia / estado según pais
        jQuery(document).ready(function() {
            console.log('jquery load');
            jQuery('#country_id').change(function(e) {
                e.preventDefault();
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
                    }
                });
                jQuery.ajax({
                    url: "/states/" + $(this).val(),
                    method: 'GET',
                    success: function(states) {

                        //Asignamos los estados
                        var old = $('#state_id').data('old') != '' ? $('#state_id').data('old') :'';
                        jQuery('#state_id').empty();
                        jQuery('#state_id').append("<option selected>Selecione una provincia / estado</option>");
                        jQuery('#city_id').empty();
                        jQuery('#city_id').append("<option selected>Seleccione una ciudad</option>");
                        jQuery.each(states, function(index, value) {
                            jQuery('#state_id').append(
                                "<option value='" + value.id +"'" + (old == value.id ? 'selected' : '') + ">" + value.name +"</option>"
                            );
                        })

                    }
                });
            });
        });

        // Obtener ciudad según estado
        jQuery(document).ready(function() {
            console.log('jquery load');
            jQuery('#state_id').change(function(e) {
                e.preventDefault();
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
                    }
                });
                jQuery.ajax({
                    url: "/cities/" + $(this).val(),
                    method: 'GET',
                    success: function(cities) {

                        //Asignamos las ciudades
                        var old = $('#city_id').data('old') != '' ? $('#city_id').data('old') :'';
                        jQuery('#city_id').empty();
                        jQuery('#city_id').append("<option selected>Seleccione una ciudad</option>");
                        jQuery.each(cities, function(index, value) {
                            jQuery('#city_id').append(
                                "<option value='" + value.id +"'" + (old == value.id ? 'selected' : '') + ">" + value.name +"</option>"
                            );
                        })

                    }
                });
            });
        });

    </script>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex justify-content-between">
                            {{ __('Usuarios') }}

                            <a href="{{ route('users.create') }}">
                                {{ __('Nuevo') }}
                            </a>

                        </div>
                    </div>

                    <div class="card-body">

                        <table class="table">

                            <form method="GET" action="{{ route('users.index') }}">
                                @csrf
                                <input class="form-control" name="search" list="datalistOptions" id="exampleDataList"
                                    placeholder="Buscar por nombre, cedula, telefono, email...">
                            </form>

                            <thead>
                                <tr>
                                    <th scope="col">Identificador</th>
                                    <th scope="col">Nombre</th>
                                    <th scope="col">Cédula</th>
                                    <th scope="col">Número Celular</th>
                                    <th scope="col">Fecha de Nacimiento</th>
                                    <th scope="col">Edad</th>
                                    <th scope="col">Ciudad</th>
                                    <th scope="col">Email</th>
                                    <th scope="col">Opciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                    <tr>
                                        <th scope="row">{{ $user->id }}</th>
                                        <td>{{ $user->name }}</td>
                                        <td>{{ $user->person->dni }}</td>
                                        <td>{{ $user->person->phone->mobile_phone }}</td>
                                        <td>{{ $user->person->date_birth }}</td>
                                        <td>{{ date('Y') - date('Y', strtotime($user->person->date_birth)) }}</td>
                                        <td>{{ $user->person->city->name }}</td>
                                        <td>{{ $user->email }}</td>
                                        <td>
                                            <a href="{{ route('users.edit', $user->id) }}"
                                                class="bnt">Editar</a>
                                            <form method="POST" action="{{ route('users.destroy', $user->id) }}">
                                                @csrf
                                                {{ method_field('DELETE') }}
                                                <button class="btn-sm bg-danger text-white" type="submit">Delete</button>
                                            </form>

                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div class="d-flex justify-content-center">
                            {{ $users->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection